# config.yaml
superplayers_file: ../../players/superplayers.json
tournament_result_history_file: results/match_results_history.csv
tournament_result_by_generation_file: results/match_results_by_generation.csv
uber_jar: &UBER_JAR ../../target/tablut_uber_jar.jar
process_log_folder: ./logs

server:
  jar: *UBER_JAR
  main_class: it.unibo.ai.didattica.competition.tablut.server.Server
  parameters: ["-t", "2000"]
  log_file: server.logs

client:
  jar: *UBER_JAR
  timeout: 1
  server_ip: localhost

starting_elo: 1500
k_factor: 32

gen_alg_popsize: 2
gen_alg_num_children: 10
gen_alg_num_generations: 10
gen_alg_delta: 0.4
gen_alg_sigma: 0.3
gen_alg_base_superplayers_path: ../../players/base_superplayers.json
gen_alg_superplayers_path: ../../players/superplayers.json
gen_alg_final_population_path: ../../players/final_population.json
gen_alg_mock: True


logger_level: INFO




